spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/courses
#    username: postgres
#    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generated-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  h2:
    console:
      enabled: true

message: Hello from test profile

#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#message: Hello from prod profile